kumuluzee:
  name: prpo-polnilnice
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PolnilniceDS
      connection-url: jdbc:postgresql://localhost:5432/polnilnice
      username: postgres
      password: postgres
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi-spec
    scan:
      packages: si.fri.prpo.polnilnice.v1
    servers: http://localhost:8080/v1
    ui:
      mapping: /openapi
      server-auto-config:
        enabled: false
        original-uri-check: false