kumuluzee:
  name: prpo-polnilnice
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PolnilniceDS
      connection-url: jdbc:postgresql://localhost:5432/polnilnice
      username: postgres
      password: postgres
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi-spec
    scan:
      packages: si.fri.prpo.polnilnice.v1
    servers: http://localhost:8080/v1
    ui:
      mapping: /openapi
      server-auto-config:
        enabled: false
        original-uri-check: false
  dev:
    scan-libraries:
      - entitete
  security:
    keycloak:
      json:
        '{"realm": "polnilnice-realm",
            "bearer-only": true,
            "auth-server-url": "http://localhost:8082/auth/",
            "ssl-required": "external",
            "resource": "polnilnice-api",
            "confidential-port": 0}'
  health:
    checks:
      data-source-health-check:
        connection-url: jdbc:postgresql://localhost:5432/polnilnice
        username: postgres
        password: postgres
        type: both
      http-health-check:
        connection-url: http://localhost:8080/servlet
        type: liveness
      disk-space-health-check:
        threshold: 100
        type: readiness
integrations:
  ocenepolnilnic:
    baseurl: "http://localhost:8081/v1"